function out1 = center_of_mass_state(Y)
%CENTER_OF_MASS_STATE
%    OUT1 = CENTER_OF_MASS_STATE(Y)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    22-Oct-2018 12:19:55

t2 = Y(1);
t3 = Y(2);
t4 = Y(3);
t5 = t2+t3;
t6 = Y(4);
t7 = t2+t3+t4+t6;
t8 = t2+t3+t4;
t9 = sin(t2);
t10 = sin(t7);
t11 = Y(6);
t12 = sin(t5);
t13 = Y(7);
t14 = sin(t8);
t15 = Y(8);
t16 = cos(t2);
t17 = cos(t7);
t18 = Y(9);
t19 = t11+t13+t15+t18;
t20 = cos(t5);
t21 = t11+t13;
t22 = cos(t8);
t23 = t11+t13+t15;
out1 = [t16.*(7.0./8.0)+t17.*(1.0./8.0)+t20.*(5.0./8.0)+t22.*(3.0./8.0);t9.*(7.0./8.0)+t10.*(1.0./8.0)+t12.*(5.0./8.0)+t14.*(3.0./8.0)+Y(5);t9.*t11.*(-7.0./8.0)-t10.*t19.*(1.0./8.0)-t12.*t21.*(5.0./8.0)-t14.*t23.*(3.0./8.0);t11.*t16.*(7.0./8.0)+t17.*t19.*(1.0./8.0)+t20.*t21.*(5.0./8.0)+t22.*t23.*(3.0./8.0)+Y(10)];
