function out1 = ground_force(Y)
%GROUND_FORCE
%    OUT1 = GROUND_FORCE(Y)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    22-Oct-2018 11:02:05

t2 = Y(7);
t3 = Y(1);
t4 = Y(2);
t5 = Y(6);
t6 = Y(3);
t7 = Y(8);
t8 = Y(4);
t9 = t3+t4+t6+t8;
t10 = sin(t9);
t11 = Y(9);
t12 = t2+t5+t7+t11;
t13 = t10.*t12.*(1.0./2.0);
t14 = t3+t4;
t15 = sin(t14);
t16 = t2+t5;
t17 = t15.*t16.*(5.0./2.0);
t18 = t3+t4+t6;
t19 = sin(t18);
t20 = t2+t5+t7;
t21 = t19.*t20.*(3.0./2.0);
out1 = -t7.*(t13+t21)-t5.*(t13+t17+t21+t5.*sin(t3).*(7.0./2.0))-t2.*(t13+t17+t21)-t10.*t11.*t12.*(1.0./2.0)+9.81e2./2.5e1;
